name: dispatch target file updated
on:
  push:
jobs:
  dispatch-target-updated:
    strategy:
      matrix:
        repo: ['km-blip/cpp-library']
    name: dispatch-target-updated
    runs-on: ubuntu-latest
    steps:
      - name: dispatch target-updated
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: target-updated
      - run: echo "${GITHUB_REF_CONTEXT#refs/heads/}"
        env:
          GITHUB_REF_CONTEXT: ${{ github.ref }}
      - shell: bash
        run: |
          echo "${GITHUB_REF_CONTEXT#refs/heads/}" > hoge.txt
      - name: Extract branch name
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: .hoge.txt
      - name: test
          ls -la
