name: dispatch target file updated
on:
  push:
jobs:
  dispatch-target-updated:
    strategy:
      matrix:
        repo: ['km-blip/cpp-library']
    name: dispatch-target-updated
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
            echo "::set-output name=PR_REPO::${GITHUB_REF#refs/*/}"
        id: step-env
      - name: dispatch target-updated
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: target-updated
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repo": " ${{ steps.step-env.outputs.PR_REPO}} "}'

