name: dispatch target file updated
on:
  push:
jobs:
  dispatch-target-updated:
    strategy:
      matrix:
        repo: ['km-blip/cpp-library']
    name: dispatch-target-updated
    runs-on: ubuntu-latest
    steps:
      
      - uses: peter-evans/repository-dispatch@v1
      - run: echo "PR_REPO=${GITHUB_REF#refs/*/}"" >> $GITHUB_ENV
      - name: dispatch target-updated
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: target-updated
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repo": " ${{PR_REPO}} "}'
