name: dispatch target file updated
on:
  push:
jobs:
  dispatch-target-updated:
    strategy:
      matrix:
        repo: ['km-blip/cpp-library']
    name: dispatch-target-updated
    runs-on: ubuntu-latest
    steps:
      - name: dispatch target-updated
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: target-updated
      - run: echo "${GITHUB_REF#refs/heads/}"
      - run: echo "${GITHUB_REF_CONTEXT#refs/heads/}"
        env:
          GITHUB_REF_CONTEXT: ${{ github.ref }}
